### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Kushwaha2021** [saran-surya/email_auth_node#21]
Please add a feature for recipient mail address visibility in mail format. Like here "to: mukeshdj19@gmail.com" is visible.
![Screenshot (133)](https://user-images.githubusercontent.com/91123190/147727630-8d54b10e-e1b7-46a6-a606-032c75703666.png)

**Comment by Kushwaha2021** [comment]
I got solution for recipient mail address visible .

**Comment by saran-surya** [comment]
Kindly create a PR, It will be reviewed and merged,
> The option is to set the params in the python file, Please make sure that the default value is set to bcc And it can be changed on request.

Thanks

**Comment by Kushwaha2021** [comment]
> 

what is PR? will you please explain it. I  am new to github

**Comment by saran-surya** [comment]
> > 
> 
> what is PR? will you please explain it. I am new to GitHub

PR is the short form meaning PULL REQUEST, So you will have to fork from a repo A, and then make your changes, rebase with any latest changes from repo A. And then you can create a PR to the repo and your code changes will be merged after a review. by this you will added as a contributor to the repo A

**Comment by Kushwaha2021** [comment]
> > > 
> > 
> > 
> > what is PR? will you please explain it. I am new to GitHub
> 
> PR is the short form meaning PULL REQUEST, So you will have to fork from a repo A, and then make your changes, rebase with any latest changes from repo A. And then you can create a PR to the repo and your code changes will be merged after a review. by this you will added as a contributor to the repo A

OK. got it
