### ISSUE TITLE
I/flutter (18471): Unable to access server

### ISSUE THREAD

**Issue by mbsim08** [saran-surya/email_auth_node#32]
I/flutter (18471): email-auth >> Remote server is not available -- using test server --
I/flutter (18471): email-auth >> ❗ Warning this is not reliable on production
I/flutter (18471): --- Package Error ---
I/flutter (18471): Unable to access server. 😑
I/flutter (18471): --- End Package Error ---
I/flutter (18471): Failed to send the verification code

I followed every step from [https://saran-surya.github.io/email-auth-node/](url)

Do I only add **server** and **serverKey** from env file?
is **serverKey** indication the randomly generated **SERVER_API_KEY** in config.env ?

If so, I am still getting this error

**Comment by mbsim08** [comment]
Don't we have to add Config Vars in Heroku's settings? I don't think it's ever mentioned in the instruction. Even after I did, I am not receiving OTP when I sent the verification code although it says that the code is sent successfully. So I tried sending again, and again, but it says it's failed to send AND unable to connect to remote server eventually.

**Comment by mbsim08** [comment]
I have resolved the issue. I am closing it.

**Comment by saran-surya** [comment]
Thankyou for your time. Please mention what was your issue, It might help other people.
