### ISSUE TITLE
Allow users to choose between google or outlook.

### ISSUE THREAD

**Issue by iOSCuriosity** [saran-surya/email_auth_node#37]
I've been able to successfully replace smtp settings of gmail to outlook and the code is working fine with that. I've already tested this with my flutter app and its working now.

Step 1: 
https://github.com/saran-surya/email_auth_node/blob/7e7a7ee70778bf34efd0bb968ecf76599a301c20/server/mailer.py#L86

replace `smtp.gmail.com` to `smtp.office365.com`

Step 2:
https://github.com/saran-surya/email_auth_node/blob/7e7a7ee70778bf34efd0bb968ecf76599a301c20/server/mailer.py#L29

replace `Auth@gmail.com` to `your outlook account`

Done!

**Comment by saran-surya** [comment]
Hi, @iOSCuriosity,
So good to hear the news, Now the test servers are working fine, and there is a patch for using GMAIL directly. Also it would be a nice addition to add outlook to the process as it will help people choose from the servers that they are comfortable with. 

Thanks again, Kindly create a PR with an example and it will be added in the next patch of the production server. 
Happy coding.

**Comment by saran-surya** [comment]
Hi, 
I am currently closing this issue die to inactivity, Kindly feel free to comment back. I will reopen the ticket

**Comment by saran-surya** [comment]
Hi, This will be added as a patch in the latest version. Thanks for the effort
