### ISSUE TITLE
Enabling less secure apps

### ISSUE THREAD

**Issue by ammar-bay** [saran-surya/email_auth_node#41]
As google has disabled less secure apps option since 30 May, 2022, what is the alternative to use this package in my flutter app?

**Comment by saran-surya** [comment]
Yes, I kindly request you to check the documentation 😅

Kindly use test servers.

**Comment by saran-surya** [comment]
Hi @ammar-bay , You can use production servers with outlook as an alternative to the project / You can also try out other alternatives such as pocketbase, supabase, firebase etc..
