### ISSUE TITLE
Package Error Unable to access server. 😑

### ISSUE THREAD

**Issue by champ96k** [saran-surya/email_auth_node#56]
I setup everything as per this [documentation](https://saran-surya.github.io/email-auth-node/) and it's working fine, but when i try to send OTP i get this error 

```
flutter: --- Package Error ---
flutter: Unable to access server. 😑
flutter: --- End Package Error ---
```

Screenshot 

<img width="691" alt="Screenshot 2022-07-04 at 1 59 01 AM" src="https://user-images.githubusercontent.com/50237575/177056238-a899b30a-c187-4b11-ac36-274d8d362e99.png">

@saran-surya do have any idea why this happenings ?

### Edit: 
Every time they are showing me different error

<img width="691" alt="Screenshot 2022-07-04 at 2 10 25 AM" src="https://user-images.githubusercontent.com/50237575/177056605-f23991b8-3e8c-4f2e-a616-a03b8f4aa8e3.png">

For same credentials 

<img width="691" alt="Screenshot 2022-07-04 at 2 25 30 AM" src="https://user-images.githubusercontent.com/50237575/177057044-41fd6499-6e62-47d9-aaa3-c50f1f67da65.png">

Thanks in advance :)

**Comment by saran-surya** [comment]
You can now use an outlook email ID instead of python and follow the same steps as per the documentation. It works fine as expeted.
