### ISSUE TITLE
Server Error 

### ISSUE THREAD

**Issue by usmanovrustam** [saran-surya/email_auth_node#68]
Message from server :: (535, b'5.7.3 Authentication unsuccessful [LO4P123CA0361.GBRP123.PROD.OUTLOOK.COM 2023-12-05T04:03:56.836Z 08DBF5221A614593]')
PYTHON SERVER :: Server error -> Mailing section

**Comment by saran-surya** [comment]
Hi can you provide the complete logs, A small piece of info cannot help in diagnosis

**Comment by eunbeek** [comment]
I also have same error, 
![image](https://github.com/saran-surya/email_auth_node/assets/50673489/6861873c-2875-42f2-8fa6-6218248638cb)

**Comment by saran-surya** [comment]
So this is issue with your Outlook credentials, check them.
Clearly not an issue with the package.

**Comment by saran-surya** [comment]
Closing this issue as it is stale, Please feel free to comment back to re-open the ticket
