### ISSUE TITLE
email-auth-node --version

### ISSUE THREAD

**Issue by Abhis2004** [saran-surya/email_auth_node#8]
email-auth-node : File C:\Users\araj8\AppData\Roaming\npm\email-auth-node.ps1 cannot be loaded because running scripts is disabled on this 
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ email-auth-node --version
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by saran-surya** [comment]
Hi @Abhis2004 as per your latest QA i belive this issue is solved, I am closing this. Feel free to comment back and I'll open the issue.
